apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment
  labels:
    app: api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: ghcr.io/emann-salah/garden-api:08f04203e1be70fd84685773ab39e939b28d5007

          command:
            - gunicorn
          args:
            - app:app
            - -b
            - 0.0.0.0:80
            - --workers
            - "4"

          ports:
            - containerPort: 80

          env:
            - name: PGHOST
              value: postgres

            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB

            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD


